---
format: 
   revealjs:
      embed-resources: true
      theme: serif
      slide-level: 3
      slide-number: true
      toc-depth: 2
      show-slide-number: all
      preview-links: auto
      number-sections: true
      link-color: orange
      smaller: true
title: "Causality"
bibliography: assets/bib.bib
---

```{r, include = FALSE}

source("assets/setup.R")

```

## Potential outcomes and the counterfactual approach

*Causation as difference making*

### Motivation {.smaller}

 
The *intervention* based motivation for understanding causal effects:

-   We want to know if a particular intervention (like aid) caused a particular outcome (like reduced corruption).
-   We need to know:
    1.  What happened?
    2.  What would the outcome have been if there were no intervention?
-   The problem:
    1.  ... this is hard
    2.  ... this is impossible

The problem in 2 is that you need to know what would have happened if things were different. You need information on a **counterfactual**.
 

### Potential Outcomes  {.smaller}
 

-   For each unit, we assume that there are two **post-treatment** outcomes: $Y_i(1)$ and $Y_i(0)$.
    -   $Y(1)$ is the outcome that *would* obtain *if* the unit received the treatment.
    -   $Y(0)$ is the outcome that *would* obtain *if* it did not.
-   The **causal effect** of Treatment (relative to Control) is: $\tau_i = Y_i(1) - Y_i(0)$
-   Note:
    -   The causal effect is defined at the *individual level*.
    -   There is no "data generating process" or functional form.
    -   The causal effect is defined relative to something else, so a counterfactual must be conceivable (did Germany cause the second world war?).
    -   Are there any substantive assumptions made here so far?
 

### Potential Outcomes

**Idea**: A causal claim is (in part) a claim about something that did not happen. This makes it metaphysical.

### Potential Outcomes

Now that we have a concept of causal effects available, let's answer two **questions**:

-   TRANSITIVITY: If for a given unit $A$ causes $B$ and $B$ causes $C$, does that mean that $A$ causes $C$?

### Potential Outcomes

 
Now that we have a concept of causal effects available, let's answer two **questions**:

-   TRANSITIVITY: If for a given unit $A$ causes $B$ and $B$ causes $C$, does that mean that $A$ causes $C$?

-   A boulder is flying down a mountain. You duck. This saves your life.

-   So the boulder caused the ducking and the ducking caused you to survive.

-   So: *did the boulder cause you to survive?*
 


### Causal claims: Contribution or attribution?

The counterfactual model is about contribution and attribution in a very specific sense.

-   Focus is on *non-rival* contributions
-   Focus is on *conditional* attribution. Not: "what caused $Y$?" or "What is *the* cause of $Y$?", but "did $X$ cause $Y$ given all other factors were what they were?"

### Causal claims: Contribution or attribution?

Consider an outcome $Y$ that might depend on two causes $X_1$ and $X_2$:

$$Y(0,0) = 0$$ $$Y(1,0) = 0$$ $$Y(0,1) = 0$$ $$Y(1,1) = 1$$

What caused $Y$? Which cause was most important?



### Causal claims: No causation without manipulation

-   Some seemingly causal claims not admissible.
-   To get the definition off the ground, manipulation must be imaginable (whether practical or not)
-   This renders thinking about effects of race and gender difficult
  -   What does it mean to say that Aunt Pat voted for Brexit because she is old?

### Causal claims: No causation without manipulation

-   Some seemingly causal claims not admissible.
-   To get the definition off the ground, manipulation must be imaginable (whether practical or not)
-   This renders thinking about effects of race and gender difficult
-   **Compare**: What does it mean to say that Southern counties voted for Brexit because they have many old people?

- More uncomfortably: What does it mean to say that the tides are caused by the moon? What exactly do we have to imagine...

### Causal claims: Causal claims are everywhere

-   Jack exploited Jill

-   It's Jill's fault that bucket fell

-   Jack is the most obstructionist member of Congress

-   Melania Trump stole from Michelle Obama's speech

-   Activists need causal claims



