---
format: 
   revealjs:
      embed-resources: true
      theme: serif
      slide-level: 3
      slide-number: true
      toc-depth: 2
      show-slide-number: all
      preview-links: auto
      number-sections: true
      link-color: orange
      smaller: true
title: "Updating in CausalQueries"
bibliography: assets/bib.bib
---


```{r, include = FALSE}
library(DeclareDesign)
library(CausalQueries)
source("assets/setup.R")

run <- FALSE

```

### Big picture

`CausalQueries` brings these elements together by allowing users to:

1. Make model: Specify a DAG: `CausalQueries` figures out all principal strata and place probabilities on these (parameters)
2. Query model: `CausalQueries` figures out which parameters correspond to a given causal query

### Illustration 1

```{r}
model <- make_model('X -> M -> Y') |>
  set_restrictions(decreasing("X", "M"))

model |>
  query_model(
    query = "Y[X=1] != Y[X=0]",
    given = c("X==1 & Y ==1", 
              "M==0", 
              "M==1",
              "X==1 & Y ==1 & M==0",
              "X==1 & Y ==1 & M==1"),
    using = "parameters"
)

```
