---
format: 
   html:
      embed-resources: true
      theme: serif
      preview-links: auto
      number-sections: true
      link-color: orange
title: "Causal models for qualitative and mixed methods inference"
subtitle: "Exercise 4: Mixed methods"
author: "Macartan Humphreys and Alan Jacobs"
bibliography: assets/bib.bib
---

```{r, include = FALSE}

options(future.globals.maxSize = 3 * 1024^3)  # 2GB
set.seed(1)
library(knitr)
source("assets/setup.R")
knitr::opts_chunk$set(echo = TRUE)

```

Choose your exercise. If you brought your own data, now please try to Part 1 A otherwise do Part 1 B.


# Part 1 A: Own data exercise


1. Define your model
2. Update your model on your data
3. Compute a query using posteriors and compare to inferences based on priors
4. Figure out what inferences you might draw for a case conditional on different within case observations you might observe

see [hoop_example](hoop_example.html)

**OR:**


# Part 1 B: A hoop test anda  smoking gun test justified with data

**(60 minutes)**

## Hoops

Sometimes we treat the absence of an expected mediator as strong evidence against a proposition. 
In this exercise we will try to *justify* a claim of this form:


1. Define a model in which $X \rightarrow M \rightarrow Y$ but do *not* impose any other restrictions
2. Imagine you saw 20 cases in which $X$ and $M$ are very highly correlated and $M$ and $Y$ are very highly correlated. Generate data like this and update the model.
3. Now imagine you saw a case in which $X=1$ and $Y=1$. What should you believe about the probability that $X$ caused $Y$?
3. Now imagine you saw in addition that $M=1$. What should you believe about the probability that $X$ caused $Y$?
4. Now imagine you saw instead that $M=0$. What should you believe about the probability that $X$ caused $Y$?



## Smoking guns

Can you construct another model and background data that lets you treat $K$ as a smoking gun evidence for the $X$ causing $Y$?

Try to generate a model and data structure that would justify smoking gun inferneces. Demonstrate on an updated model that these inferences are valid.

# Closing discussion
**(30 minutes)**



